& { $BinaryFormatter = New-Object -TypeName System.Runtime.Serialization.Formatters.Binary.BinaryFormatter
 @{ 
'InfoBodyPanel.Name' = 'InfoBodyPanel'
'ColumnHeader1.Name' = 'ColumnHeader1'
'Label1.Name' = 'Label1'
'InfoHeaderPanel.Name' = 'InfoHeaderPanel'
'lblConversionStatus.Name' = 'lblConversionStatus'
'TabPage1.Name' = 'TabPage1'
'Refresh_Button.Name' = 'Refresh_Button'
'Label6.Name' = 'Label6'
'Label7.Name' = 'Label7'
'pbPercentEncrypted.Name' = 'pbPercentEncrypted'
'TabPage2.Name' = 'TabPage2'
'Label2.Name' = 'Label2'
'Label3.Name' = 'Label3'
'Label5.Name' = 'Label5'
'lblPersistentVolumeId.Name' = 'lblPersistentVolumeId'
'lblVersion.Name' = 'lblVersion'
'Label8.Name' = 'Label8'
'lblProtectionStatus.Name' = 'lblProtectionStatus'
'lvProtectors.Name' = 'lvProtectors'
'Panel1.Name' = 'Panel1'
'btnRefreshPercent.Name' = 'btnRefreshPercent'
'Panel2.Name' = 'Panel2'
'lblVolumeLockStatus.Name' = 'lblVolumeLockStatus'
'VolumesComboBox.Name' = 'VolumesComboBox'
'lblPercentEncrypted.Name' = 'lblPercentEncrypted'
'Label4.Name' = 'Label4'
'$this.Name' = 'BDEGUIInfoForm'
'ColumnHeader2.Name' = 'ColumnHeader2'
'lblDeviceId.Name' = 'lblDeviceId'
'TabControl1.Name' = 'TabControl1'
}
}