& { $BinaryFormatter = New-Object -TypeName System.Runtime.Serialization.Formatters.Binary.BinaryFormatter
 @{ 
'Label1.Name' = 'Label1'
'TextBox3.Name' = 'TextBox3'
'ComboBox1.Name' = 'ComboBox1'
'Label5.Name' = 'Label5'
'Label2.Name' = 'Label2'
'Label3.Name' = 'Label3'
'TextBox1.Name' = 'TextBox1'
'$this.Name' = 'BDEGUIUnlockForm'
'TextBox9.Name' = 'TextBox9'
'Label7.Name' = 'Label7'
'TextBox8.Name' = 'TextBox8'
'Label9.Name' = 'Label9'
'Label4.Name' = 'Label4'
'TextBox7.Name' = 'TextBox7'
'TextBox2.Name' = 'TextBox2'
'TextBox6.Name' = 'TextBox6'
'TextBox10.Name' = 'TextBox10'
'TextBox11.Name' = 'TextBox11'
'Label6.Name' = 'Label6'
'Label10.Name' = 'Label10'
'TextBox5.Name' = 'TextBox5'
'TextBox4.Name' = 'TextBox4'
'Label8.Name' = 'Label8'
'OK_Button.Name' = 'OK_Button'
'Cancel_Button.Name' = 'Cancel_Button'
'RPS1.Name' = 'RPS1'
'RPS2.Name' = 'RPS2'
'RPS3.Name' = 'RPS3'
'RPS4.Name' = 'RPS4'
'RPS5.Name' = 'RPS5'
'RPS6.Name' = 'RPS6'
'RPS7.Name' = 'RPS7'
'RPS8.Name' = 'RPS8'
}
}